### ISSUE TITLE
Consider not hiding the working directory?

### ISSUE THREAD

**Issue by ellismg** [bryanar/rover#5]
Having the working directory prefixed with . makes it hard to discover.  Would it be possible to name it "work" or "src" or something?  Perhaps we could consolidate the output to look like this:

```
<rid>
    |--- src
           |--- corecr
           |--- corefx
           |--- core-setup
           |--- libuv
    |--- obj
           |--- source tarball?
    |--- bin
           | --- dotnet
           | --- shared
           | --- sdk
```

**Comment by bryanar** [comment]
Hm, yes. When it finishes successfully it gets removed anyways.

**Comment by bryanar** [comment]
Changed my mind after further thinking about it - I want to understand the request better.

**Comment by bryanar** [comment]
Given that this is developer tooling, no more hiding the inner workings. I'll adopt this setup.

**Comment by bryanar** [comment]
Done. Moving the code to dotnet/core though.
